/* eslint-disable import/prefer-default-export */
export const GLOBAL_START_DRAFT = 'GLOBAL_START_DRAFT';

export const PLAYERS_FETCH = 'PLAYERS_FETCH';
export const PLAYERS_UPDATE = 'PLAYERS_UPDATE';

export const DRAFTS_FETCH = 'DRAFTS_SELECT';
export const DRAFTS_GET = 'DRAFTS_GET';
export const DRAFTS_CREATE = 'DRAFTS_CREATE';
export const DRAFTS_START = 'DRAFTS_START';
export const DRAFTS_ROSTER_ADD = 'DRAFTS_ROSTER_ADD';
export const DRAFTS_ROSTER_REMOVE = 'DRAFTS_ROSTER_REMOVE';
export const DRAFTS_PLAYERS_ADD = 'DRAFTS_PLAYERS_ADD';
export const DRAFTS_PLAYERS_REMOVE = 'DRAFTS_PLAYERS_REMOVE';
